### ISSUE TITLE
Local data model for Subscribie

### ISSUE THREAD

**Issue by chrisjsimpson** [Subscribie/subscribie#136]
**Summary**: Subscribie does not currently store much information in its local database, instead, during customer sign-up it writes to external apis and then fetches information back from the same external apis (e.g. the GoCardless api for transactions, and mandates). 

There is a need however to store plan history, e.g. when a plan/sku changes or is deleted, its important to keep track of this, because otherwise plans may be deleted with active customers leaving no history. External apis cannot be used for this because it's within the domain/business logic of Subscribie.

**Motivation:**  As a shop admin, when I delete an sku from my shop which has existing subscribers then I should still be able to see the original sku (plan) which they signed up with on my dashboard, the related sku is just archived. 

For this to work Subscribie needs to store a history of skus, related customers and probably more.

**Detail:**

Currently Subscribie only stores the person object in its local database during customer sign-up: https://github.com/Subscribie/subscribie/blob/510b54f59f71867757756f955e65098a88af9a6b/subscribie/views.py#L87

Subscribie does _not_ locally store any of the following:

- The transactions/payments customers make, instead these are fetched from the GoCardless api:

https://github.com/Subscribie/subscription-management-software/blob/647a6cc25eba363f105c3d546d553740b304b779/GoCardless.py#L119 

- The plan/sku a customer signed up for:

Subscribie currently sends the sku title to GoCardless when creating a subscription. This is how subscriptions are currently matched to plans
 https://github.com/Subscribie/subscribie/blob/510b54f59f71867757756f955e65098a88af9a6b/subscribie/views.py#L326

**Proposed implementation draft** 

There are at-least two items to implementing this:

- [x] https://github.com/Subscribie/subscribie/issues/137 As a shop admin, when an sku is created, it MUST be assigned a uuid which never changes in preperation for when we store the exact sku/plan details which a customer signed up to. An sku, and all of its information (price, selling points, title) must be immutable: 
    - "never changes" is complex: if a shop owner wants to change the price of an sku or other information, then a new sku  should be created and the old sku archived, preserving the original which may have subscribers.

- [x] https://github.com/Subscribie/subscribie/issues/138 As a customer, after signing up to a subscription, the uuid of the sku is stored against my customer record

- [x] #141 A migrations approach for the data model e.g. using https://flask-sqlalchemy.palletsprojects.com/en/2.x/quickstart/ and https://flask-migrate.readthedocs.io/en/latest/
(the existing strategy is basic)

Next steps:

Code an initial implementation of sku's getting a uuid and storing sku uuids against customers during sign-up.

**Comment by chrisjsimpson** [comment]
We now have a datamodel which can be migrated using flask_migrate / sqlalchemy alembic
