### ISSUE TITLE
Remove jamla yaml based config

### ISSUE THREAD

**Issue by chrisjsimpson** [Subscribie/subscribie#167]
Motivation: Simplify make it boring

Switch to sqlalchemy for sku items

- [x] Replace jamla.py class with sqlalchemy models 
- [x] Update deployment process
  - [x] Merge in module seo changes to master https://github.com/Subscribie/module-seo-page-title/pull/2
  - [x] Merge Jesmond theme changes to master https://github.com/Subscribie/theme-jesmond/pull/3
  - [x] Merge deployer changes to master https://github.com/Subscribie/subscribie-deployer/pull/2
  - [x] Merge in builder theme to master https://github.com/Subscribie/theme-builder/pull/9
  - [x] Merge in Subscribie remove jamla changes https://github.com/Subscribie/subscribie/pull/181

..
- [x] Update theme builder
- [x] Update module builder
- [x] Update subscribie
- [x] Migrate db
- [x] Update deployer module
