### ISSUE TITLE
Migrate to bootstrap

### ISSUE THREAD

**Issue by Svyatoslav-Polishchuk** [Subscribie/subscribie#191]
Currently, the admin part is built using Bulma framework. It has some limitations and a much smaller community. It has been decided to migrate to the Bootstrap framework.

**Comment by Anpoli13** [comment]
Pages need to be migrated:
- [ ] add_item;

- [ ] cancel_mandates_confirm;

- [ ] connect_gocardless_manually;

- [ ] connect_google_tag_manager_manually;

- [ ] connect_tawk_manually;

- [ ] customers;

- [ ] delete_item_choose;

- [ ] edit;

- [ ] transactions;
