### ISSUE TITLE
As a customer I can log into my account edit details and manage my subscription

### ISSUE THREAD

**Issue by KatherineAS** [Subscribie/subscribie#205]
**Is your feature request related to a problem? Please describe.**
Customers do not have access to an account where these details are easily accessible. Nor are they able to easily update their subscription.

**Describe the solution you'd like**
For the customer to have an account to log into where they can track and update their information such as email address and payent methods and to manage their subscription (eg pause cancel or add an aditional subscripption)

**Describe alternatives you've considered**
Customers can currently cancel their membership by cancelling their direct debit and alter their payment method through GoCardless. There is no option to update their details or pause or amend their sunscription without contacting the company directly

- [ ] Allow customers to create an account when they subscribe to a package
- [ ] Allow customers to update their details such as name, payment details and email address
- [ ] Allow customers to pause their subscription
- [ ] Allow customers to cancel their subscription
