### ISSUE TITLE
Documentation - how to create a new theme

### ISSUE THREAD

**Issue by chrisjsimpson** [Subscribie/subscribie#58]
Background: A theme developer wants to create/view/edit themes. They may want to do this locally for testing, they may want to be able to push these themes to production and view them as a real shop

- [x] Scenario View/analyse: As a theme designer, I want to be able to view different existing themes on my local machine https://github.com/Subscribie/subscribiecli/issues/7
- [ ] Scenario 2: As a theme designer, I want to be able to deploy my theme as a live subscribie shop's theme https://github.com/Subscribie/subscribie/issues/60
- [x] Scenario 3: As a theme designer, I want to see the edits I make to a theme locally, see my theme as I develop it  https://github.com/Subscribie/subscribiecli/issues/8
- [x] Update Subscribie cli to python3 https://github.com/Subscribie/subscribiecli/issues/6
- [ ] #59 Record short video on how to do local theme development
- [ ] How to deploy a theme to production via api call EDIT: This is an epic and needs its own sprint
- [x] Publish latest version of subscribie to pypi (blocking #https://github.com/Subscribie/subscribiecli/issues/7

**Comment by chrisjsimpson** [comment]
https://subscribe.readthedocs.io/en/latest/

**Comment by chrisjsimpson** [comment]
Docs added https://subscribie.readthedocs.io/en/latest/tasks/create-a-theme.html 
Closed https://github.com/Subscribie/subscribiecli/issues/8
@Svyatoslav-Polishchuk :tada:
